build:
 verbosity: detailed
image: Visual Studio 2017
platform: x64
environment:
  matrix:
   - COMMIT: 031e494
     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
   - COMMIT: HEAD
     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
build_script:
 - |-
    git clone https://github.com/microsoft/vcpkg.git
    cd %APPVEYOR_BUILD_FOLDER%\vcpkg
    git reset --hard %COMMIT%
    git status
    git show HEAD --no-patch
    call bootstrap-vcpkg.bat
    %APPVEYOR_BUILD_FOLDER%\vcpkg\vcpkg.exe version
    %APPVEYOR_BUILD_FOLDER%\vcpkg\vcpkg.exe --triplet x64-windows install pthreads
    cd %APPVEYOR_BUILD_FOLDER%
    cmake -H%APPVEYOR_BUILD_FOLDER% -Bbuild -DCMAKE_TOOLCHAIN_FILE=%APPVEYOR_BUILD_FOLDER%\vcpkg\scripts\buildsystems\vcpkg.cmake -G"Visual Studio 15 2017 Win64"
    cmake --build build --config Release -- /m
